server:
  port: 8083

spring:
  application:
    name: ms-coordinadores

  datasource:
      url: jdbc:postgresql://${DB_HOST:${POSTGRES_HOST:localhost}}:${DB_PORT:5432}/${DB_NAME:asesoriasdb}
      username: ${DB_USER:coordinadores}
      password: ${DB_PASSWORD:coordinadores_pass}
      driver-class-name: org.postgresql.Driver
      hikari:
        maximum-pool-size: 5
        connection-timeout: 30000

  jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate.default_schema: coordinadores
        hibernate.jdbc.time_zone: UTC

  main:
      allow-bean-definition-overriding: true

